// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// login
export const DEBIT_CARD_INFO_REQUEST = 'DEBIT_CARD_INFO_REQUEST';
export const UPDATE_DEBIT_CARD = "UPDATE_DEBIT_CARD"
export const DEBIT_CARD_INFO_SUCCESS = 'DEBIT_CARD_INFO_SUCCESS';
export const DEBIT_CARD_INFO_FAILURE = 'DEBIT_CARD_INFO_FAILURE';